== Overview

=== Preface

The "Data Classification and Encoding Guide" has been developed to provide
consistent, standardized instructions for encoding S-124 compliant
Navigational Warning Data. This document has been laid out, as far as
practical, along the lines of the Joint IMO/IHO/WMO Manual on Maritime Safety
Information (MSI), IHO Publication S-53. It should be noted that although S-53
covers the spectrum of MSI, S-124 focuses only on Navigational Warnings.

The purpose of the Data Classification and Encoding Guide is to facilitate
S-124 encoding to meet IHO standards for the proper display of Navigational
Warnings in an ECDIS. The document describes how to encode information that
the Maritime Safety Information Provider considers worthy of a navigational
warning. The content of a S-124 Navigational Warning dataset is at the
discretion of the producing authority provided that the conventions described
within this document are followed.

The entire S-100 Standard, including the S-124 Navigational Warning Product
Specification, is available at the following web site, https://iho.int/.

=== S-124 Annex A; Data Classification and Encoding Guide -- Metadata

NOTE: This information uniquely identifies this Annex to the Product
Specification and provides information about its creation and maintenance.

*Title*:: The International Hydrographic Organization Electronic Navigational
Chart Product Specification, Annex A -- Data Classification and Encoding Guide

*Version*:: 2.0.0

*Date*:: March 2025

*Language*:: English

*Classification*:: Unclassified

*Contact*:: International Hydrographic Organization +
4b, quai Antoine 1er +
B.P. 445 +
MC 98011 MONACO CEDEX +
Telephone: +377 93 10 81 00 +
Fax: +377 93 10 81 40 +
Email: mailto:info@iho.int[info@iho.int]

*URL*:: http://www.iho.int/[www.iho.int]

*Identifier*:: S-124 Annex A

*Maintenance*:: Changes to S-124 Annex A; Data Classification and Encoding
Guide are coordinated by the S-124 Project Team (S-124PT), a Project Team
under the IHO World-Wide Navigational Warning Sub-Committee (WWNWS-SC)

=== Terms, Definitions and Abbreviations

==== Use of language

Within this document:

* "Must" indicates a mandatory requirement.
* "Should" indicates an optional requirement, that is the recommended process
to be followed, but is not mandatory.
* "May" means "allowed to" or "could possibly", and is not mandatory.

=== Maintenance

Changes to the Data Classification and Encoding Guide must occur in accordance
with the <<S124,clause="1.7">>.
